apiVersion: apps/v1
kind: Deployment
metadata:
  name: clara-mq
spec:
  selector:
    matchLabels:
      app: clara-mq
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: clara-mq
        tier: backend
        track: stable
    spec:
      containers:
        - name: clara-mq
          image: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15673
---
apiVersion: v1
kind: Service
metadata:
  name: clara-mq
spec:
  selector:
    app: clara-mq
    tier: backend
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clara-redis
spec:
  selector:
    matchLabels:
      app: clara-redis
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: clara-redis
        tier: backend
        track: stable
    spec:
      containers:
        - name: clara-redis
          image: redis:6.0.5-alpine3.12
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: clara-redis
spec:
  selector:
    app: clara-redis
    tier: backend
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: clara-backend-server
  name: clara-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clara-backend-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clara-backend-server
    spec:
      containers:
        - name: clara-backend-server
          imagePullPolicy: Never
          # PLEASE RUN `docker build . -t clara-backend:latest`
          image: clara-backend:latest
          command: ["/bin/sh", "-c", "npm run start"]
          ports:
            - containerPort: 5555
      # initContainers:
      #   - name: clara-mq
      #     image: rabbitmq
      #     command: ["rabbitmq-server", "-detached"]
      #     ports:
      #       - containerPort: 5672
      #       - containerPort: 15672
      #       - containerPort: 15673
